# Generated by Django 5.2.5 on 2025-09-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMarcas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 't_marcas',
            },
        ),
        migrations.CreateModel(
            name='TVentas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publicacion_mlm_id', models.CharField(max_length=255)),
                ('venta_id', models.BigIntegerField(blank=True, null=True)),
                ('titulo', models.TextField()),
                ('sku', models.CharField(max_length=255)),
                ('fecha_venta', models.DateTimeField()),
                ('marca', models.CharField(max_length=255)),
                ('precio_unitario', models.FloatField(blank=True, null=True)),
                ('unidades', models.BigIntegerField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 't_ventas',
            },
        ),
        migrations.CreateModel(
            name='TCategorias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('marca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tmarcas')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 't_categorias',
            },
        ),
        migrations.CreateModel(
            name='TProductos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_tachado', models.FloatField(blank=True, null=True)),
                ('precio_oferta', models.FloatField(blank=True, null=True)),
                ('total_stock', models.BigIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tcategorias')),
                ('marca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tmarcas')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 't_productos',
            },
        ),
        migrations.CreateModel(
            name='TProductoCompetencias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('precio_tachado', models.FloatField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('marca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tmarcas')),
                ('productos_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tproductos')),
            ],
            options={
                'verbose_name': 'ProductoCompetencia',
                'verbose_name_plural': 'ProductosCompetencia',
                'db_table': 't_productos_competencia',
            },
        ),
        migrations.CreateModel(
            name='TPublicacionesProductos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_mlm', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tcategorias')),
                ('marca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tmarcas')),
                ('producto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tproductos')),
            ],
            options={
                'verbose_name': 'PublicacionesProductos',
                'verbose_name_plural': 'PublicacionesProductos',
                'db_table': 't_publicaciones_productos',
            },
        ),
    ]
