# Generated by Django 5.2.5 on 2025-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVentas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publicacion_mlm_id', models.CharField(max_length=255)),
                ('venta_id', models.BigIntegerField(blank=True, null=True)),
                ('titulo', models.TextField()),
                ('sku', models.CharField(max_length=255)),
                ('fecha_venta', models.DateTimeField()),
                ('marca', models.CharField(max_length=255)),
                ('precio_unitario', models.FloatField(blank=True, null=True)),
                ('unidades', models.BigIntegerField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 't_ventas',
            },
        ),
    ]
