# Generated by Django 5.2.5 on 2025-09-04 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMarca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 't_marcas',
            },
        ),
        migrations.CreateModel(
            name='TProductos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('total_stock', models.BigIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('marca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tmarca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 't_productos',
            },
        ),
        migrations.CreateModel(
            name='TProductoCompetencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('marca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tmarca')),
                ('productos_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tproductos')),
            ],
            options={
                'verbose_name': 'ProductoCompetencia',
                'verbose_name_plural': 'ProductosCompetencia',
                'db_table': 't_productos_competencia',
            },
        ),
    ]
