# Generated by Django 5.2.5 on 2025-09-13 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_seed_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproductocompetencias',
            name='productos_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competidores', to='venta.tproductos'),
        ),
    ]
