# Generated by Django 5.2.5 on 2025-09-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_tmarca_tproductos_tproductocompetencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tproductos',
            name='marca',
        ),
    ]
