# Generated by Django 5.2.5 on 2025-09-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_remove_tproductos_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='tproductos',
            name='precio_techo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
